function problems = stgeo_problem(dims, opts)
    if nargin < 1, dims = 3; end
    if nargin < 2, opts = struct(); end
    if ~isfield(opts, 'seed'), opts.seed = 9527; end
    if ~isfield(opts, 'scale'), opts.scale = 0.7; end

    addpath(fullfile(fileparts(mfilename('fullpath')), 'src'));
    addpath(fullfile(fileparts(mfilename('fullpath')), 'mex'));
    compile_mex();

    nd = length(dims);
    problems = cell(nd, 1);

    rng(opts.seed); 

    disp(["Test problem(s) generated by the seed: ", opts.seed])

    idx = 1;
    for p = dims
        n = 2 * p;
        T0 = 2 * rand(n) - 1;
        T0 = 0.5 * (T0 - T0');
        T0(p+1:n, p+1:n) = 0;
        %Qs = expm(T0);
        %S  = mex_sblas_logm(Qs);
        problems{idx} = (pi * opts.scale / norm(T0, 2)) * T0;
        idx = idx + 1;
    end
end
